global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'spring-saas-core'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app_a:8080', 'app_b:8080']
        labels:
          app: 'spring-saas-core'
